exports.games = {
	name: String,
	type: String,
	ranked: String,
	numberOfPlayers: Number,
	players: {},
	playersById: {},
	playerScores: {},
	currentPlayer: String,
	winner: String,
	winString: String,
	draw: String,
	requestedDraw: String,
	acceptedDraw: {},
	surrendered: {},
	startSetup: {},
	moves: [],
	currentSetup: {},
	endSetup: {}
};
